import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786724492175 implements MigrationInterface {
    name = 'InitialSchema1786724492175'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "dispute_cases_bulk" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voyage_id" uuid NOT NULL, "type" character varying(20) NOT NULL, "amount_disputed" numeric(12,2) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'Open', "created_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "resolved_date" TIMESTAMP WITH TIME ZONE, "final_settlement_amount" numeric(12,2), CONSTRAINT "PK_c1afa61aa126910b3e8672e46e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_disputes_status" ON "dispute_cases_bulk" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_disputes_voyage" ON "dispute_cases_bulk" ("voyage_id") `);
        await queryRunner.query(`CREATE TABLE "laytime_calculations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voyage_id" uuid NOT NULL, "version" integer NOT NULL DEFAULT '1', "allowed_laytime" interval NOT NULL, "used_laytime" interval NOT NULL, "demurrage_amount" numeric(12,2) NOT NULL DEFAULT '0', "despatch_amount" numeric(12,2) NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'Draft', "calculated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2300fc277baf16e54a86784bd9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_laytime_calc_voyage" ON "laytime_calculations" ("voyage_id") `);
        await queryRunner.query(`CREATE TABLE "nor_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voyage_id" uuid NOT NULL, "file_path" character varying(500) NOT NULL, "tender_time" TIMESTAMP WITH TIME ZONE NOT NULL, "accepted_time" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8d8ffc3d43b917cd70f8ddc9d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_nor_voyage" ON "nor_documents" ("voyage_id") `);
        await queryRunner.query(`CREATE TABLE "sof_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sof_id" uuid NOT NULL, "event_time" TIMESTAMP WITH TIME ZONE NOT NULL, "event_type" character varying(50) NOT NULL, "remarks" text, "confidence_score" numeric(3,2), "is_manual_override" boolean NOT NULL DEFAULT false, "override_reason" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c1330bd993d8c5d6cd58566cef1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sof_events_type" ON "sof_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "idx_sof_events_sof_time" ON "sof_events" ("sof_id", "event_time") `);
        await queryRunner.query(`CREATE TABLE "sof_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voyage_id" uuid NOT NULL, "file_path" character varying(500) NOT NULL, "upload_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "status" character varying(20) NOT NULL DEFAULT 'Draft', CONSTRAINT "PK_44bec7528e4d4bd1ff1acb27ce2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sof_documents_voyage" ON "sof_documents" ("voyage_id") `);
        await queryRunner.query(`CREATE TABLE "container_milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "time" TIMESTAMP WITH TIME ZONE NOT NULL, "container_id" uuid NOT NULL, "event_type" character varying(30) NOT NULL, "location" character varying(100), "source" character varying(50) NOT NULL, "is_correction" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f275a79f1a05603d00615e64a87" PRIMARY KEY ("id", "time"))`);
        await queryRunner.query(`CREATE INDEX "idx_milestones_container" ON "container_milestones" ("container_id", "time") `);
        await queryRunner.query(`CREATE TABLE "dispute_cases_container" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "amount_disputed" numeric(12,2) NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'Open', "created_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "resolved_date" TIMESTAMP WITH TIME ZONE, "final_settlement_amount" numeric(12,2), CONSTRAINT "PK_5706af1e31aefabe491eef39902" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_container_disputes_status" ON "dispute_cases_container" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_container_disputes_invoice" ON "dispute_cases_container" ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "dd_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "carrier_name" character varying(100) NOT NULL, "invoice_date" TIMESTAMP WITH TIME ZONE NOT NULL, "due_date" TIMESTAMP WITH TIME ZONE NOT NULL, "total_amount" numeric(12,2) NOT NULL, "file_path" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_881ef39e9ea3f3e02d0d58457ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dd_invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "container_id" uuid NOT NULL, "charge_type" character varying(20) NOT NULL, "claimed_days" integer NOT NULL, "claimed_rate" numeric(10,2) NOT NULL, "claimed_amount" numeric(10,2) NOT NULL, CONSTRAINT "PK_31bd153856abf15e8749ac4db3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_invoice_lines_container" ON "dd_invoice_lines" ("container_id") `);
        await queryRunner.query(`CREATE INDEX "idx_invoice_lines_invoice" ON "dd_invoice_lines" ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "carrier_tariffs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "carrier_name" character varying(100) NOT NULL, "contract_ref" character varying(100), "effective_date" date NOT NULL, "port" character varying(10) NOT NULL, "free_time_days" integer NOT NULL, "detention_tiers" jsonb NOT NULL, "demurrage_tiers" jsonb, CONSTRAINT "PK_84a068771513229fa745dc43ee8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tariffs_carrier_port" ON "carrier_tariffs" ("carrier_name", "port") `);
        await queryRunner.query(`CREATE TABLE "free_time_clocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "container_id" uuid NOT NULL, "tariff_id" uuid NOT NULL, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "expiry_time" TIMESTAMP WITH TIME ZONE NOT NULL, "free_time_used" interval NOT NULL DEFAULT '0', "demurrage_accrued" numeric(10,2) NOT NULL DEFAULT '0', "detention_accrued" numeric(10,2) NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'Active', CONSTRAINT "PK_97d4b3103b41b071eefe2b40974" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_clocks_status_expiry" ON "free_time_clocks" ("status", "expiry_time") `);
        await queryRunner.query(`CREATE INDEX "idx_clocks_container" ON "free_time_clocks" ("container_id") `);
        await queryRunner.query(`CREATE TABLE "containers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "container_number" character varying(11) NOT NULL, "type" character varying(20) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d215a4e1f8d1be24d123df3d9e5" UNIQUE ("container_number"), CONSTRAINT "PK_21cbac3e68f7b1cf53d39cda70c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_containers_number" ON "containers" ("container_number") `);
        await queryRunner.query(`CREATE TABLE "shipment_containers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shipment_id" uuid NOT NULL, "container_id" uuid NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0ca94196495b071938dedcb1a22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ship_cont_container" ON "shipment_containers" ("container_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ship_cont_shipment" ON "shipment_containers" ("shipment_id") `);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_ref" character varying(100) NOT NULL, "bill_of_lading" character varying(100), "origin" character varying(10) NOT NULL, "destination" character varying(10) NOT NULL, "consignee" character varying(200), "shipper" character varying(200), "vessel_id" uuid, "voyage_ref" character varying(50), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_shipments_consignee" ON "shipments" ("consignee") `);
        await queryRunner.query(`CREATE INDEX "idx_shipments_booking" ON "shipments" ("booking_ref") `);
        await queryRunner.query(`CREATE TABLE "vessels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "imo" character varying(7) NOT NULL, "name" character varying(100) NOT NULL, "flag" character varying(50) NOT NULL, "type" character varying(50) NOT NULL, "dwt" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2d6ec4ab5558afb7ee5e3fff9d7" UNIQUE ("imo"), CONSTRAINT "PK_be5a5b1f0d546d8bec08e0d1583" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_vessels_type" ON "vessels" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_vessels_imo" ON "vessels" ("imo") `);
        await queryRunner.query(`CREATE TABLE "voyages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vessel_id" uuid NOT NULL, "charter_party_id" uuid, "cargo_quantity" numeric(10,2) NOT NULL, "cargo_type" character varying(100) NOT NULL, "load_port" character varying(10) NOT NULL, "discharge_port" character varying(10) NOT NULL, "laycan_start" date NOT NULL, "laycan_end" date NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'Planned', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_1228deefdd7d500c4fe501fd3e" UNIQUE ("charter_party_id"), CONSTRAINT "chk_voyages_status" CHECK ("status" IN ('Planned', 'Active', 'Completed', 'Cancelled')), CONSTRAINT "PK_78cc29cefa039ab389f74b7bfe5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_voyages_ports" ON "voyages" ("load_port", "discharge_port") `);
        await queryRunner.query(`CREATE INDEX "idx_voyages_status" ON "voyages" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_voyages_vessel" ON "voyages" ("vessel_id") `);
        await queryRunner.query(`CREATE TABLE "charter_parties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "voyage_id" uuid NOT NULL, "form_type" character varying(50) NOT NULL, "full_text" text NOT NULL, "effective_date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_ac10a00f187eb6871bd89620ad" UNIQUE ("voyage_id"), CONSTRAINT "PK_0846c1c9e895a370263cd8989ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_charter_parties_voyage" ON "charter_parties" ("voyage_id") `);
        await queryRunner.query(`CREATE TABLE "cp_clauses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "charter_party_id" uuid NOT NULL, "clause_type" character varying(50) NOT NULL, "raw_text" text NOT NULL, "parameters" jsonb NOT NULL, CONSTRAINT "PK_c7603c126757925057183d121e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_cp_clauses_type" ON "cp_clauses" ("clause_type") `);
        await queryRunner.query(`CREATE INDEX "idx_cp_clauses_cp" ON "cp_clauses" ("charter_party_id") `);
        await queryRunner.query(`CREATE TABLE "calculation_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "calculation_id" uuid NOT NULL, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "end_time" TIMESTAMP WITH TIME ZONE NOT NULL, "period_type" character varying(20) NOT NULL, "applied_clause_id" uuid, CONSTRAINT "PK_dd476fad7029373c7b553fc1b62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_calc_periods_calc" ON "calculation_periods" ("calculation_id") `);
        await queryRunner.query(`CREATE TABLE "counterparties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "type" character varying(20) NOT NULL, "imo_company_id" character varying(50), CONSTRAINT "PK_9f045dc184ca2426af5e9dfb13b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_counterparties_name" ON "counterparties" ("name") `);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid, "action" character varying(100) NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" uuid NOT NULL, "old_value" jsonb, "new_value" jsonb, "ip_address" inet, "metadata" jsonb, CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_entity" ON "audit_log" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_timestamp" ON "audit_log" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "feedback_signals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_type" character varying(30) NOT NULL, "source_id" uuid NOT NULL, "user_id" uuid NOT NULL, "rating" character varying(10) NOT NULL, "correction_text" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5db8b669b7ef6c51100bbc20b2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_feedback_source" ON "feedback_signals" ("source_type", "source_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firebase_uid" character varying(128) NOT NULL, "email" character varying(255) NOT NULL, "full_name" character varying(200) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_login" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_0fd54ced5cc75f7cb92925dd803" UNIQUE ("firebase_uid"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_users_firebase" ON "users" ("firebase_uid") `);
        await queryRunner.query(`CREATE TABLE "ai_interactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "session_id" character varying(100) NOT NULL, "prompt" text NOT NULL, "response" text NOT NULL, "retrieved_context" jsonb, "model_version" character varying(50) NOT NULL, "feedback_score" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3d775287d9543a6d92d5151a31c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ai_interactions_session" ON "ai_interactions" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ai_interactions_user" ON "ai_interactions" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "knowledge_base_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_type" character varying(30) NOT NULL, "source_ref" character varying(500) NOT NULL, "text_chunk" text NOT NULL, "embedding" vector(1536) NOT NULL, "last_updated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_bcf29235d7bca14c1f0a166890b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_kb_source" ON "knowledge_base_chunks" ("source_type", "source_ref") `);
        await queryRunner.query(`ALTER TABLE "dispute_cases_bulk" ADD CONSTRAINT "FK_44f2accd4aa03dac32e9b6d00c1" FOREIGN KEY ("voyage_id") REFERENCES "voyages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laytime_calculations" ADD CONSTRAINT "FK_629c260dd78156b15d7f29f2ba2" FOREIGN KEY ("voyage_id") REFERENCES "voyages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nor_documents" ADD CONSTRAINT "FK_bbbfb326634632fcc077dc33984" FOREIGN KEY ("voyage_id") REFERENCES "voyages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sof_events" ADD CONSTRAINT "FK_949d3c2a468bc414562a119d06a" FOREIGN KEY ("sof_id") REFERENCES "sof_documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sof_documents" ADD CONSTRAINT "FK_d12b8eca4764f6108b85ac4e223" FOREIGN KEY ("voyage_id") REFERENCES "voyages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "container_milestones" ADD CONSTRAINT "FK_8433de8e3ef38d06e1eca937bfa" FOREIGN KEY ("container_id") REFERENCES "containers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispute_cases_container" ADD CONSTRAINT "FK_833495d1a8e116f3d9a64d22ff1" FOREIGN KEY ("invoice_id") REFERENCES "dd_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dd_invoice_lines" ADD CONSTRAINT "FK_7a176bc744668c48317fbbc0f80" FOREIGN KEY ("invoice_id") REFERENCES "dd_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dd_invoice_lines" ADD CONSTRAINT "FK_b551add5c123435567e8bcad395" FOREIGN KEY ("container_id") REFERENCES "containers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "free_time_clocks" ADD CONSTRAINT "FK_310f67c6523cae863047ad1ee9c" FOREIGN KEY ("container_id") REFERENCES "containers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "free_time_clocks" ADD CONSTRAINT "FK_bf2527890fc715578708ee60fc2" FOREIGN KEY ("tariff_id") REFERENCES "carrier_tariffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_containers" ADD CONSTRAINT "FK_f54cc67712f5a181a5fc089d151" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment_containers" ADD CONSTRAINT "FK_0840576e087e4f349c6984ad4a5" FOREIGN KEY ("container_id") REFERENCES "containers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipments" ADD CONSTRAINT "FK_ffa1869a5df7b77d15663ece1ed" FOREIGN KEY ("vessel_id") REFERENCES "vessels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voyages" ADD CONSTRAINT "FK_a47ca774f74441931ace7246b20" FOREIGN KEY ("vessel_id") REFERENCES "vessels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voyages" ADD CONSTRAINT "FK_1228deefdd7d500c4fe501fd3e6" FOREIGN KEY ("charter_party_id") REFERENCES "charter_parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charter_parties" ADD CONSTRAINT "FK_ac10a00f187eb6871bd89620ad4" FOREIGN KEY ("voyage_id") REFERENCES "voyages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cp_clauses" ADD CONSTRAINT "FK_14ed4cb222957e5a271229adc9f" FOREIGN KEY ("charter_party_id") REFERENCES "charter_parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calculation_periods" ADD CONSTRAINT "FK_5eca659fc448fc6e41b1d6365fc" FOREIGN KEY ("calculation_id") REFERENCES "laytime_calculations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calculation_periods" ADD CONSTRAINT "FK_c48bd839e3164f252405660bf70" FOREIGN KEY ("applied_clause_id") REFERENCES "cp_clauses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback_signals" ADD CONSTRAINT "FK_a961cc11e34ca3c0ed1995d6e55" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" ADD CONSTRAINT "FK_745b66db11c0c988b44334626d5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_interactions" DROP CONSTRAINT "FK_745b66db11c0c988b44334626d5"`);
        await queryRunner.query(`ALTER TABLE "feedback_signals" DROP CONSTRAINT "FK_a961cc11e34ca3c0ed1995d6e55"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7"`);
        await queryRunner.query(`ALTER TABLE "calculation_periods" DROP CONSTRAINT "FK_c48bd839e3164f252405660bf70"`);
        await queryRunner.query(`ALTER TABLE "calculation_periods" DROP CONSTRAINT "FK_5eca659fc448fc6e41b1d6365fc"`);
        await queryRunner.query(`ALTER TABLE "cp_clauses" DROP CONSTRAINT "FK_14ed4cb222957e5a271229adc9f"`);
        await queryRunner.query(`ALTER TABLE "charter_parties" DROP CONSTRAINT "FK_ac10a00f187eb6871bd89620ad4"`);
        await queryRunner.query(`ALTER TABLE "voyages" DROP CONSTRAINT "FK_1228deefdd7d500c4fe501fd3e6"`);
        await queryRunner.query(`ALTER TABLE "voyages" DROP CONSTRAINT "FK_a47ca774f74441931ace7246b20"`);
        await queryRunner.query(`ALTER TABLE "shipments" DROP CONSTRAINT "FK_ffa1869a5df7b77d15663ece1ed"`);
        await queryRunner.query(`ALTER TABLE "shipment_containers" DROP CONSTRAINT "FK_0840576e087e4f349c6984ad4a5"`);
        await queryRunner.query(`ALTER TABLE "shipment_containers" DROP CONSTRAINT "FK_f54cc67712f5a181a5fc089d151"`);
        await queryRunner.query(`ALTER TABLE "free_time_clocks" DROP CONSTRAINT "FK_bf2527890fc715578708ee60fc2"`);
        await queryRunner.query(`ALTER TABLE "free_time_clocks" DROP CONSTRAINT "FK_310f67c6523cae863047ad1ee9c"`);
        await queryRunner.query(`ALTER TABLE "dd_invoice_lines" DROP CONSTRAINT "FK_b551add5c123435567e8bcad395"`);
        await queryRunner.query(`ALTER TABLE "dd_invoice_lines" DROP CONSTRAINT "FK_7a176bc744668c48317fbbc0f80"`);
        await queryRunner.query(`ALTER TABLE "dispute_cases_container" DROP CONSTRAINT "FK_833495d1a8e116f3d9a64d22ff1"`);
        await queryRunner.query(`ALTER TABLE "container_milestones" DROP CONSTRAINT "FK_8433de8e3ef38d06e1eca937bfa"`);
        await queryRunner.query(`ALTER TABLE "sof_documents" DROP CONSTRAINT "FK_d12b8eca4764f6108b85ac4e223"`);
        await queryRunner.query(`ALTER TABLE "sof_events" DROP CONSTRAINT "FK_949d3c2a468bc414562a119d06a"`);
        await queryRunner.query(`ALTER TABLE "nor_documents" DROP CONSTRAINT "FK_bbbfb326634632fcc077dc33984"`);
        await queryRunner.query(`ALTER TABLE "laytime_calculations" DROP CONSTRAINT "FK_629c260dd78156b15d7f29f2ba2"`);
        await queryRunner.query(`ALTER TABLE "dispute_cases_bulk" DROP CONSTRAINT "FK_44f2accd4aa03dac32e9b6d00c1"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kb_source"`);
        await queryRunner.query(`DROP TABLE "knowledge_base_chunks"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_interactions_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_interactions_session"`);
        await queryRunner.query(`DROP TABLE "ai_interactions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_firebase"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_feedback_source"`);
        await queryRunner.query(`DROP TABLE "feedback_signals"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_entity"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP INDEX "public"."idx_counterparties_name"`);
        await queryRunner.query(`DROP TABLE "counterparties"`);
        await queryRunner.query(`DROP INDEX "public"."idx_calc_periods_calc"`);
        await queryRunner.query(`DROP TABLE "calculation_periods"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cp_clauses_cp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cp_clauses_type"`);
        await queryRunner.query(`DROP TABLE "cp_clauses"`);
        await queryRunner.query(`DROP INDEX "public"."idx_charter_parties_voyage"`);
        await queryRunner.query(`DROP TABLE "charter_parties"`);
        await queryRunner.query(`DROP INDEX "public"."idx_voyages_vessel"`);
        await queryRunner.query(`DROP INDEX "public"."idx_voyages_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_voyages_ports"`);
        await queryRunner.query(`DROP TABLE "voyages"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vessels_imo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vessels_type"`);
        await queryRunner.query(`DROP TABLE "vessels"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shipments_booking"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shipments_consignee"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ship_cont_shipment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ship_cont_container"`);
        await queryRunner.query(`DROP TABLE "shipment_containers"`);
        await queryRunner.query(`DROP INDEX "public"."idx_containers_number"`);
        await queryRunner.query(`DROP TABLE "containers"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clocks_container"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clocks_status_expiry"`);
        await queryRunner.query(`DROP TABLE "free_time_clocks"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tariffs_carrier_port"`);
        await queryRunner.query(`DROP TABLE "carrier_tariffs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoice_lines_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoice_lines_container"`);
        await queryRunner.query(`DROP TABLE "dd_invoice_lines"`);
        await queryRunner.query(`DROP TABLE "dd_invoices"`);
        await queryRunner.query(`DROP INDEX "public"."idx_container_disputes_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."idx_container_disputes_status"`);
        await queryRunner.query(`DROP TABLE "dispute_cases_container"`);
        await queryRunner.query(`DROP INDEX "public"."idx_milestones_container"`);
        await queryRunner.query(`DROP TABLE "container_milestones"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sof_documents_voyage"`);
        await queryRunner.query(`DROP TABLE "sof_documents"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sof_events_sof_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sof_events_type"`);
        await queryRunner.query(`DROP TABLE "sof_events"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nor_voyage"`);
        await queryRunner.query(`DROP TABLE "nor_documents"`);
        await queryRunner.query(`DROP INDEX "public"."idx_laytime_calc_voyage"`);
        await queryRunner.query(`DROP TABLE "laytime_calculations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_disputes_voyage"`);
        await queryRunner.query(`DROP INDEX "public"."idx_disputes_status"`);
        await queryRunner.query(`DROP TABLE "dispute_cases_bulk"`);
    }

}
